name: Publish a Github release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*"

jobs:
  release:
    runs-on: debian-latest
    permissions:
      contents: write
    steps:
      - name: Release
        uses: softprops/action-gh-release@v1

